name: Test Application

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Create test environment file
      run: |
        cat > .env << EOF
        NODE_ENV=test
        PORT=3000
        OPENAI_API_KEY=test-key
        PINECONE_API_KEY=test-key
        PINECONE_ENVIRONMENT=test
        PINECONE_INDEX_NAME=test
        SUPABASE_URL=https://test.supabase.co
        SUPABASE_ANON_KEY=test-key
        TWILIO_ACCOUNT_SID=test-sid
        TWILIO_AUTH_TOKEN=test-token
        WEBHOOK_BASE_URL=http://localhost:3000
        EOF

    - name: Run linting (if available)
      run: |
        if npm run lint --silent 2>/dev/null; then
          npm run lint
        else
          echo "No linting script found, skipping..."
        fi
      continue-on-error: true

    - name: Run unit tests (if available)
      run: |
        if npm test --silent 2>/dev/null; then
          npm test
        else
          echo "No test script found, skipping..."
        fi
      continue-on-error: true

    - name: Test application startup
      run: |
        echo "🚀 Testing application startup..."
        timeout 30s npm start &
        APP_PID=$!
        
        # Wait for app to start
        sleep 10
        
        # Test health endpoint
        if curl -f http://localhost:3000/health; then
          echo "✅ Application started successfully"
        else
          echo "❌ Application health check failed"
          exit 1
        fi
        
        # Clean up
        kill $APP_PID 2>/dev/null || true

    - name: Test integration endpoints
      run: |
        echo "🧪 Running integration tests..."
        node test-twilio-integration.js || echo "Integration tests completed"

  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run security audit
      run: |
        npm audit --audit-level=moderate || true
        echo "Security audit completed"

    - name: Check for secrets in code
      run: |
        echo "🔍 Checking for accidentally committed secrets..."
        
        # Look for actual API keys (not sanitization patterns)
        SECRET_FOUND=false
        
        # Check for actual OpenAI keys (sk- followed by 48+ chars, not in sanitization context)
        if grep -r "sk-[a-zA-Z0-9]\{48,\}" --include="*.js" --include="*.json" --exclude-dir=node_modules . | grep -v "REDACTED" | grep -v "sanitize"; then
          echo "⚠️ Potential OpenAI API key found!"
          SECRET_FOUND=true
        fi
        
        # Check for actual Pinecone keys (not in sanitization context)  
        if grep -r "pcsk_[a-zA-Z0-9_]\{48,\}" --include="*.js" --include="*.json" --exclude-dir=node_modules . | grep -v "REDACTED" | grep -v "sanitize"; then
          echo "⚠️ Potential Pinecone API key found!"
          SECRET_FOUND=true
        fi
        
        # Check for JWT tokens (not in sanitization context)
        if grep -r "eyJ[a-zA-Z0-9_-]\{20,\}" --include="*.js" --include="*.json" --exclude-dir=node_modules . | grep -v "sanitize" | grep -v "example"; then
          echo "⚠️ Potential JWT token found!"
          SECRET_FOUND=true
        fi
        
        # Check for other common secret patterns
        if grep -r "Bearer [a-zA-Z0-9_-]\{20,\}" --include="*.js" --include="*.json" --exclude-dir=node_modules .; then
          echo "⚠️ Potential Bearer token found!"
          SECRET_FOUND=true
        fi
        
        if [ "$SECRET_FOUND" = true ]; then
          echo "Please review and remove any hardcoded API keys"
          exit 1
        else
          echo "✅ No secrets detected in code"
        fi